#!/bin/bash

RED=red
DEMOENTRY=demos/demo.red

case $1 in
    demo)
        $RED -o demo -c $DEMOENTRY
    ;;
    clean)
        rm -f demo $TARGET libRedRT* 
    ;;
    *)
        echo Usage: build.sh [command]
        echo
        echo [command]:
        echo "    demo    Build demos."
        echo "    clean   Clean all files that generated by command demo."
esac
